---
# tasks file for freckles-config

- name: (potentially) changing local config file
  freckles_config:
    freckles_config_tasks: "{{ freckles_config_tasks }}"

- name: checking out repos
  local_action: git repo="{{ item.url }}" dest="{{ item.path }}" track_submodules=yes update="{{ freckles_config_update_repos }}"
  when: "item.url"
  with_items: "{{ freckles_config_tasks.get('enable_repos', []) | expand_repos_filter }}"

- name: updating repos
  local_action: git repo="{{ item.url }}" dest="{{ item.path }}" track_submodules=yes update="{{ freckles_config_update_repos }}"
  when: "item.url and freckles_config_update_repos and not freckles_config_tasks.get('enable_repos', False)"
  with_items: "{{ freckles_file_config.get('trusted-repos', []) | expand_repos_filter }}"
